AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with lifecycle rule and IAM user for uploading objects.

Parameters:
  BucketName:
    Description: Enter a unique name for the bucket
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: S3Uploader
      Policies:
        - PolicyName: S3UploadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource: !Sub "${S3Bucket.Arn}/*"

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket

  AccessKeyId:
    Description: Access Key ID for the IAM user
    Value: !Ref AccessKey

  SecretAccessKey:
    Description: Secret Access Key for the IAM user
    Value: !GetAtt AccessKey.SecretAccessKey